### ISSUE TITLE
Unable to generate subpages

### ISSUE THREAD

**Issue by Acsigen** [pawelsikora/mkdocs-with-confluence#17]
## Prerequisites

Hi, I have generated a documentation with the structure presented in the image below:

![image](https://user-images.githubusercontent.com/13287878/210341021-01724197-b9b0-43e9-b5c1-bb0638ec9c0a.png)

When I try to uplopad the documentation to Confluence, only `Home`, `Architecture`, and `Installation` are getting published. Nothing under the `Stacks` subpage gets uploaded to Confluence as seen in the image below:

![image](https://user-images.githubusercontent.com/13287878/210342661-6e517abe-5fb4-4a8a-ac0a-2e44982c8816.png)

## Config

This is my mkdocs.yml configuration file:

```yml
site_name: Monitoring
theme:
  name: windmill
plugins:
  - search
  - mkdocs-with-confluence:
          host_url: https://confluencebt.host/rest/api/content
          space: CONFLUENCE_SPACE
          parent_page_name: Monitorizare
          username: confluence_user
          password: confluence_password
          enabled_if_env: MKDOCS_TO_CONFLUENCE
          verbose: true
          debug: true
          dryrun: false
nav:
  - Home: "index.md"
  # - Introduction: "index.md"
  - Architecture: "architecture.md"
  - Installation: "installation.md"
  - Stacks:
    - Metrics: 
      - Architecture: "stacks/metrics/architecture.md"
      - Installation and Operation: "playbooks/metrics/README.md"
    - Logs:
      - Architecture: "stacks/logs/architecture.md"
      - Installation and Operation: "playbooks/logs/README.md"
    - Traces:
      - Architecture: "stacks/traces/architecture.md"
      - Installation and Operation: "playbooks/traces/README.md"

```

## Log entry

```text
INFO    -  Mkdocs With Confluence: Exporting MKDOCS pages to Confluence turned ON by var MKDOCS_TO_CONFLUENCE==1!
Number of Files in directory tree: 10
DEBUG    - SECTION title: Section(title='Stacks')
DEBUG    - SECTION title:     Section(title='Metrics')
DEBUG    - SECTION title:     Section(title='Logs')
DEBUG    - SECTION title:     Section(title='Traces')

DEBUG    - Handling Page 'Home' (And Parent Nav Pages if necessary):

DEBUG    - Get section first parent title...: 
DEBUG    - WRN(list index out of range): No first parent! Assuming DEBUG    - Monitorizare...
DEBUG    - None
DEBUG    - Get section second parent title...: 
DEBUG    - ERR(list index out of range) No second parent! Assuming second parent is main parent: Monitorizare...
Monitorizare
DEBUG    - ONLY ONE PARENT FOUND. ASSUMING AS A FIRST NODE after main parent config Monitorizare
DEBUG    - PARENT0: Monitorizare, PARENT1: Monitorizare, MAIN PARENT: Monitorizare

#################################################

INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: Monitorizare
URL: https://confluencebt.bt.wan/rest/api/content?title=Monitorizare&spaceKey=CONFLUENCE_SPACE&expand=history
ID: 129549192
DEBUG    - JUST ONE STEP FROM UPDATE OF PAGE 'Monitorizare' 
DEBUG    - CHECKING IF PARENT PAGE ON CONFLUENCE IS THE SAME AS HERE
INFO    -   * Mkdocs With Confluence: Find PARENT OF PAGE, PAGE NAME: Monitorizare
INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: Monitorizare
URL: https://confluencebt.bt.wan/rest/api/content?title=Monitorizare&spaceKey=CONFLUENCE_SPACE&expand=history
ID: 129549192
PARENT NAME: Documentation
DEBUG    - ERR, Parents does not match: 'Monitorizare' =/= 'Documentation' Aborting...

DEBUG    - Handling Page 'Installation and Operation' (And Parent Nav Pages if necessary):

DEBUG    - Get section first parent title...: 
DEBUG    - SECTION title: Section(title='Logs')
DEBUG    - Logs
DEBUG    - Get section second parent title...: 
DEBUG    - SECTION title: Section(title='Stacks')
Logs
DEBUG    - PARENT0: Logs, PARENT1: Stacks, MAIN PARENT: Monitorizare
```

## Question

How can I change the configurationso the plugin will create the required subpages?

**Comment by pawelsikora** [comment]
So far as I remember two pages of the same name cannot exists in one space in confluence.
([https://community.atlassian.com/t5/Confluence-questions/Two-pages-folders-with-the-same-name-within-one-space/qaq-p/1401009](https://community.atlassian.com/t5/Confluence-questions/Two-pages-folders-with-the-same-name-within-one-space/qaq-p/1401009))

Could you give it a try and rename it in navigation names, not the file names?

**Comment by Acsigen** [comment]
I tried with the following `mkdocs.yml` structure:

```YAML
nav:
  - Home: "index.md"
  # - Introduction: "index.md"
  - Architecture: "architecture.md"
  - Ansible Server Installation and Operation: "playbooks/ansible_server/README.md"
  - Metrics:
    - Metrics Architecture: "stacks/metrics/architecture.md"
    - Metrics Installation and Operation: "playbooks/metrics/README.md"
  - Logs:
    - Logs Architecture: "stacks/logs/architecture.md"
    - Logs Installation and Operation: "playbooks/logs/README.md"
  - Traces:
    - Traces Architecture: "stacks/traces/architecture.md"
    - Traces Installation and Operation: "playbooks/traces/README.md"
```
It seems that the error now is `DEBUG    - ERR, Parents does not match: 'Traces' =/= 'Monitorizare' Aborting...`.

For now I switched to a flat structure, but it would be great if a layered structure would be possible.

**Comment by Damounet** [comment]
Hey, I run into similar issues with sub folders in the navigation.

I have a space that is almost empty : 

![Image](https://github.com/user-attachments/assets/08f66f63-5114-4981-bd26-ab3719fa0d41)

I have this mkdocs configuration :

```yaml
site_name: 'TEST '
nav:
  - Home: index.md
  - NSAJ: nsaj.md
  - Test Folder:
      - Test Sub Page: installation/testSubFolder.md
logging:
  level: DEBUG
plugins:
  - techdocs-core
  - kroki:
      FileTypes:
        - svg
      FileTypeOverrides:
        plantuml: svg
        mermaid: svg
  - mkdocs-with-confluence:
      host_url: !ENV [CONFLUENCE_HOST, "https://myTenant.atlassian.net/wiki/rest/api/content"]
      space: !ENV [CONFLUENCE_SPACE, "~71202026a64e86cbe84f33aa0ca3c5ff0cab77"]
      parent_page_name: !ENV [CONFLUENCE_PARENT, "test mkdocs"]
      username: !ENV [CONFLUENCE_USER, toto]
      api_token: !ENV [CONFLUENCE_TOKEN, myToken]
      enabled_if_env: MKDOCS_TO_CONFLUENCE
      dryrun: !ENV [MKDOCS_DRYRUN, false]
      verbose: !ENV [MKDOCS_VERBOSE, true]
      debug: !ENV [MKDOCS_DEBUG, true]
  - print-site

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

When I run `mkdocs build` the end of the log is as follows :

```bash
DEBUG    - UPDATING PAGE TO CONFLUENCE, DETAILS:
DEBUG    - HOST: https://myTenant.atlassian.net/wiki/rest/api/content
DEBUG    - SPACE: ~123456789
DEBUG    - TITLE: Test Sub Page
DEBUG    - PARENT: Test Folder
DEBUG    - BODY: <h1>test include sub folder</h1>
<p>dfsgdfsgsdg
gfd
gd
fsgs
gdfdsg
sfdgf
ds</p>
<p>fdsgfdsg</p>


INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: Test Sub Page
URL: https://myTenant.atlassian.net/wiki/rest/api/content?title=Test+Sub+Page&spaceKey=~123456789&expand=history
PAGE DOES NOT EXIST
DEBUG    - PAGE: Test Sub Page, PARENT0: Test Folder, PARENT1: test mkdocs, MAIN PARENT: test mkdocs
INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: Test Folder
URL: https://myTenant.atlassian.net/wiki/rest/api/content?title=Test+Folder&spaceKey=~123456789&expand=history
PAGE DOES NOT EXIST
INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: test mkdocs
URL: https://myTenant.atlassian.net/wiki/rest/api/content?title=test+mkdocs&spaceKey=~123456789&expand=history
ID: 415629324
INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: test mkdocs
URL: https://myTenant.atlassian.net/wiki/rest/api/content?title=test+mkdocs&spaceKey=~123456789&expand=history
ID: 415629324
DEBUG    - Trying to ADD page 'Test Folder' to parent1(test mkdocs) ID: 415629324
INFO    -   * Mkdocs With Confluence: Test Folder - *NEW PAGE*
* Mkdocs With Confluence: Adding Page: PAGE NAME: Test Folder, parent ID: 415629324
  URL: https://myTenant.atlassian.net/wiki/rest/api/content/
  DATA: {'type': 'page', 'title': 'Test Folder', 'space': {'key': '~123456789'}, 'ancestors': [{'id': '415629324'}], 'body': {'storage': {'value': '<p> Test Folder </p>', 'representation': 'storage'}}}
  OK!
  INFO    -   * Mkdocs With Confluence: Test Sub Page - *NEW PAGE*
* Mkdocs With Confluence: Adding Page: PAGE NAME: Test Sub Page, parent ID: None
  URL: https://myTenant.atlassian.net/wiki/rest/api/content/
  DATA: {'type': 'page', 'title': 'Test Sub Page', 'space': {'key': '~123456789'}, 'ancestors': [{'id': None}], 'body': {'storage': {'value': '<h1>test include sub folder</h1>\n<p>dfsgdfsgsdg\ngfd\ngd\nfsgs\ngdfdsg\nsfdgf\nds</p>\n<p>fdsgfdsg</p>\n', 'representation': 'storage'}}}
  OK!
  INFO    -   * Mkdocs With Confluence: Test Sub Page - *NEW PAGE*
* Mkdocs With Confluence: Adding Page: PAGE NAME: Test Sub Page, parent ID: None
  URL: https://myTenant.atlassian.net/wiki/rest/api/content/
  DATA: {'type': 'page', 'title': 'Test Sub Page', 'space': {'key': '~123456789'}, 'ancestors': [{'id': None}], 'body': {'storage': {'value': '<h1>test include sub folder</h1>\n<p>dfsgdfsgsdg\ngfd\ngd\nfsgs\ngdfdsg\nsfdgf\nds</p>\n<p>fdsgfdsg</p>\n', 'representation': 'storage'}}}
  ERR    - HTTP error on adding page. It probably occured due to parent ID('None') page is not YET synced on server. Retry nb 1/10...
  INFO    -   * Mkdocs With Confluence: Find Page ID: PAGE NAME: Test Folder
  URL: https://myTenant.atlassian.net/wiki/rest/api/content?title=Test+Folder&spaceKey=~123456789&expand=history
  ID: 416776219
  INFO    -   * Mkdocs With Confluence: Test Sub Page - *NEW PAGE*
* Mkdocs With Confluence: Adding Page: PAGE NAME: Test Sub Page, parent ID: 416776219
  URL: https://myTenant.atlassian.net/wiki/rest/api/content/
  DATA: {'type': 'page', 'title': 'Test Sub Page', 'space': {'key': '~123456789'}, 'ancestors': [{'id': '416776219'}], 'body': {'storage': {'value': '<h1>test include sub folder</h1>\n<p>dfsgdfsgsdg\ngfd\ngd\nfsgs\ngdfdsg\nsfdgf\nds</p>\n<p>fdsgfdsg</p>\n', 'representation': 'storage'}}}
  ERROR   -  Error reading page 'installation/testSubFolder.md': 400 Client Error: Bad Request for url: https://myTenant.atlassian.net/wiki/rest/api/content/
  Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 8, in <module>
  sys.exit(cli())
  ^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
  return self.main(*args, **kwargs)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1082, in main
  rv = self.invoke(ctx)
  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
  return ctx.invoke(self.callback, **ctx.params)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 788, in invoke
  return __callback(*args, **kwargs)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/__main__.py", line 288, in build_command
  build.build(cfg, dirty=not clean)
  File "/usr/lib/python3.12/site-packages/mkdocs/commands/build.py", line 310, in build
  _populate_page(file.page, config, files, dirty)
  File "/usr/lib/python3.12/site-packages/mkdocs/commands/build.py", line 163, in _populate_page
  page.markdown = config.plugins.on_page_markdown(
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/commands/build.py", line 310, in build
  _populate_page(file.page, config, files, dirty)
  File "/usr/lib/python3.12/site-packages/mkdocs/commands/build.py", line 163, in _populate_page
  page.markdown = config.plugins.on_page_markdown(
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/plugins.py", line 635, in on_page_markdown
  return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/plugins.py", line 566, in run_event
  result = method(item, **kwargs)
  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs_with_confluence/plugin.py", line 338, in on_page_markdown
  self.add_page(page.title, parent_id, confluence_body)
  File "/usr/lib/python3.12/site-packages/mkdocs_with_confluence/plugin.py", line 545, in add_page
  r.raise_for_status()
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
  raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://myTenant.atlassian.net/wiki/rest/api/content/
```

And the confluence ends up with this structure :

![Image](https://github.com/user-attachments/assets/cdfcb718-748e-4a71-ae3f-fcd0535e08b5)

The sub page is correctl created at the top of the space outside of the "vue d'ensemble" in confluence and we can't see in the menu

![Image](https://github.com/user-attachments/assets/241bbfc6-052a-4c28-8d52-a798503a6a01)

What I see from the log, the plugin creates the "test folder" page but when it wants to create the "Test Sub Page", it can't find the ancestor ID `'ancestors': [{'id': None}]`.

Am I missing something in the configuration in the mkdocs.yml to achieve the correct behavior @pawelsikora  ?

**Comment by lupor** [comment]
There is a bug in the hierarchy fix that creates a disordered page_titles array. You need to reverse the list if it contains more than one element, before the main parent page is prepended. I'll add the correspond link to the piece of code in a minute

**Comment by lupor** [comment]
There is a bug in the hierarchy fix that creates a disordered page_titles array. You need to reverse the list if it contains more than one element, before the main parent page is prepended. I'll add the correspond link to the piece of code in a minute
